# Configuration eth1 / Ansible playbook
# VM2

- hosts: localhost
  remote_user: root
  tasks:


  - name: Configuration de VM2/eth1
    nmcli:
      type: ethernet
      conn_name: eth1 via ansible
      ifname: eth1
      state: present
      autoconnect: true
      ip4: 172.16.2.132/28

 - name: Configuration de VM2/eth2
    nmcli:
      type: ethernet
      conn_name: eth2 via ansible
      ifname: eth2
      state: present
      autoconnect: true
      ip4: 172.16.2.162/28

      


  - name: Activation explicite de cette configuration
    shell: nmcli con up "eth1 via ansible"
  - name: Activation explicite de cette configuration
    shell: nmcli con up "eth2 via ansible"



