# Configuration eth1 / Ansible playbook
# VM3

- hosts: localhost
  remote_user: root
  tasks:

  
  - name: Configuration de VM3/eth1
    nmcli:
      type: ethernet
      conn_name: eth1 via ansible
      ifname: eth1
      state: present
      autoconnect: true
      ip4: 172.16.2.163/28
  

    - name: Configuration de la route vers LAN1 via VM2
      community.general.nmcli:
      type: ethernet
      conn_name: eth1 via ansible
      ifname: eth1
      routes4: 172.16.2.128/28  172.16.2.163 
      state: present


  - name: Activation explicite de cette configuration
    shell: nmcli con up "eth1 via ansible"


